version: "3.8"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./public:/var/www/public
    ports:
      - "8080:80"
    container_name: nginxcont
    depends_on:
      - php
  php:
    image: php:8.0-fpm
    volumes:
      - ./:/var/www
    container_name: phpcont
